name: Integration Tests on AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.0"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-west-2"

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/

    - name: Run Integration Tests
      run: |
        # Install dependencies (e.g., pytest, Node.js, etc.)
        pip install pytest # Adjust for your testing framework
        # Run your tests
        pytest tests/integration_tests.py

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: terraform/
